trigger: none

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    values:
      - 'tst'
      - 'gtu'
      - 'uat'
      - 'ptp'
      - 'prd'
      - 'trainprd'
    default: 'gtu'
    
variables:
  - template: ${{ format('../variables/default_variables_{0}.yml', lower( parameters.environment )) }}

resources:
  containers:
    - container: ccoe-product
      image: belfius/gemz/ccoe-product:release-1.5.2
      endpoint: sc-acr-tooling-prod-${{ variables.applicationCode }}
  repositories:
    - repository: devops-template
      type: git
      name: geai/devops-template
#  repositories:
#    - repository: shared
#      type: git
#      name: shared      

pool:
  name: self-hosted-vmss-ubuntu-prd-we

jobs:
  - template: pipeline_templates/jobs_iac_keyvault_create.yml@devops-template
    parameters:
      azureSubscription: '${{ variables.azureSubscription }}'
      resourceGroupName: '${{ variables.resourceGroupName }}'
      keyVaultPurpose: ${{variables.keyVaultPurpose}}
      keyVaultIndex: '001'
      environment: '${{ parameters.environment }}'
      location: 'westeurope'
  - job: GenerateCsr
    container: ccoe-product
    steps:
      - checkout: none
      - bash: |
          echo "certificateSubject: " '"${{ variables.certificateSubject }}"'
          echo "dnsNames: ${{ variables.certificateDnsNames }}"
      - task: KeyVault@1
        inputs:
          azureSubscription: ${{ variables.azureSubscription }}
          action: 'createCertificate'
          keyVaultName: ${{ variables.keyvaultKubernetes }}
          certificateName: ${{ variables.certificateName }}-belwired-net
          dnsNames: ${{ variables.certificateDnsNames }}.belwired.net
          subject: ${{ variables.certificateSubject }}.belwired.net
          contentType: 'application/x-pkcs12'
          certAuthType: 'external'